# Generated by Django 4.1.7 on 2023-03-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('dateOfCreation', models.DateTimeField()),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
