# Generated by Django 4.1.7 on 2023-03-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todotask_dateofcreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='task',
            new_name='taskName',
        ),
    ]
